[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=604800"